[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true


