kind: "Service"
apiVersion: "v1"
metadata:
  name: "etcdaas-api"
  namespace: "default"
spec:
  ports:
    - name: "extension-api"
      protocol: "TCP"
      port: 443
      targetPort: 9443
      nodePort: 0
  selector: {}   
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "etcdaas-api"
  namespace: "default"
subsets: 
  - addresses:
      - ip: "192.168.137.1"
    ports:
      - name: "extension-api"
        protocol: "TCP"
        port: 9443
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.etcdaas.devoxx2018
spec:
  insecureSkipTLSVerify: true
  group: etcdaas.devoxx2018
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: etcdaas-api
    namespace: default
  version: v1alpha1