kind: ServiceAccount
apiVersion: v1
metadata:
  name: etcdaas
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcdaas:clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ClusterAdmin
subjects:
- kind: ServiceAccount
  name: etcdaas
  namespace: default